/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladoraPersistencia;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Persona;

/**
 *
 * @author alumno
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ControladoraPersistencia controlador = new ControladoraPersistencia();
    Boolean esNuevo = true;

    /**
     * Creates new form MenuPrincipall
     */
    public MenuPrincipal() {
        initComponents();
        PersonaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                Persona persona = controlador.encontrarPersona(Integer.parseInt(PersonaTable.getValueAt(PersonaTable.rowAtPoint(evt.getPoint()), 0).toString()));
                System.out.println(persona.getNombre());
                onEdit(persona);
            }
        });

        List<Persona> personas = controlador.obtenerPersonas();

        for (Persona persona : personas) {
            this.agregarPersonaTabla(persona);
        }
    }

    public void limpiarCampos() {
        this.nombreTXT.setText("");
        this.apellidoTXT.setText("");
        this.nitTXT.setText("");
        this.cuiTXT.setText("");
        this.telefonoTXT.setText("");
        this.domicilioTXT.setText("");
        this.diaTXT.setText("");
        this.mesTXT.setText("");
        this.anioTXT.setText("");
    }

    private void consolePersonalog(String texto, Color color) {
        this.errorLog.setText(texto);
        this.errorLog.setForeground(color);
    }

    private void agregarPersonaTabla(Persona persona) {
        DefaultTableModel modelo = (DefaultTableModel) this.PersonaTable.getModel();

        Object[] obj = {Integer.toString(persona.getCui()), persona.getNombre(), persona.getApellido(), Integer.toString(persona.getTelefono())};
        modelo.addRow(obj);
    }

    private void onEdit(Persona persona) {
        this.esNuevo = false;

        this.guardarBTN.setText("Actualizar");
        this.limpiarBTN.setText("Eliminar");

        this.nitTXT.setEditable(false);
        this.cuiTXT.setEditable(false);

        this.nombreTXT.setText(persona.getNombre());
        this.apellidoTXT.setText(persona.getApellido());
        this.nitTXT.setText(persona.getNit());
        this.cuiTXT.setText(Integer.toString(persona.getCui()));
        this.telefonoTXT.setText(Integer.toString(persona.getTelefono()));
        this.domicilioTXT.setText(persona.getDomicilio());
        this.diaTXT.setText(Integer.toString(persona.getFechaNacimiento().getDay()));
        this.mesTXT.setText(Integer.toString(persona.getFechaNacimiento().getMonth()));
        this.anioTXT.setText(Integer.toString(persona.getFechaNacimiento().getYear()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrincipalPanel = new javax.swing.JPanel();
        navegacionPanel = new javax.swing.JTabbedPane();
        personasPanel = new javax.swing.JPanel();
        cuiTXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PersonaTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nitTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        domicilioTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diaTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mesTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        anioTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombreTXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        apellidoTXT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        telefonoTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        guardarBTN = new javax.swing.JButton();
        limpiarBTN = new javax.swing.JButton();
        errorLog = new javax.swing.JLabel();
        nuevaPersonaBTN = new javax.swing.JButton();
        BuscarTXT = new javax.swing.JTextField();
        BuscarBTN = new javax.swing.JButton();
        vehiculosPanel = new javax.swing.JPanel();
        estacionamientosPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cuiTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuiTXTActionPerformed(evt);
            }
        });

        PersonaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUI", "Nombres", "Apellidos", "Telefono", " "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PersonaTable);
        if (PersonaTable.getColumnModel().getColumnCount() > 0) {
            PersonaTable.getColumnModel().getColumn(0).setResizable(false);
            PersonaTable.getColumnModel().getColumn(1).setResizable(false);
            PersonaTable.getColumnModel().getColumn(2).setResizable(false);
            PersonaTable.getColumnModel().getColumn(3).setResizable(false);
            PersonaTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("CUI");

        nitTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitTXTActionPerformed(evt);
            }
        });

        jLabel2.setText("NIT");

        domicilioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioTXTActionPerformed(evt);
            }
        });

        jLabel3.setText("Domicilio");

        diaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTXTActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha nacimiento");

        jLabel5.setText("dia");

        mesTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTXTActionPerformed(evt);
            }
        });

        jLabel6.setText("mes");

        anioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioTXTActionPerformed(evt);
            }
        });

        jLabel7.setText("anio");

        nombreTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTXTActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        apellidoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTXTActionPerformed(evt);
            }
        });

        jLabel9.setText("Apellido");

        telefonoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTXTActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefono");

        guardarBTN.setText("Crear");
        guardarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBTNActionPerformed(evt);
            }
        });

        limpiarBTN.setText("Limpiar");
        limpiarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBTNActionPerformed(evt);
            }
        });

        nuevaPersonaBTN.setText("Nueva Persona");
        nuevaPersonaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPersonaBTNActionPerformed(evt);
            }
        });

        BuscarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTXTActionPerformed(evt);
            }
        });

        BuscarBTN.setText("Buscar");
        BuscarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personasPanelLayout = new javax.swing.GroupLayout(personasPanel);
        personasPanel.setLayout(personasPanelLayout);
        personasPanelLayout.setHorizontalGroup(
            personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personasPanelLayout.createSequentialGroup()
                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuiTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(nitTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(domicilioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(personasPanelLayout.createSequentialGroup()
                                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mesTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(apellidoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(telefonoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personasPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpiarBTN)
                        .addGap(18, 18, 18)
                        .addComponent(guardarBTN)
                        .addGap(18, 18, 18)))
                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personasPanelLayout.createSequentialGroup()
                        .addComponent(BuscarBTN)
                        .addGap(59, 59, 59)
                        .addComponent(BuscarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nuevaPersonaBTN)
                        .addGap(19, 19, 19))
                    .addGroup(personasPanelLayout.createSequentialGroup()
                        .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLog)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        personasPanelLayout.setVerticalGroup(
            personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personasPanelLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaPersonaBTN)
                    .addComponent(BuscarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarBTN))
                .addGap(18, 18, 18)
                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuiTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nitTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domicilioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personasPanelLayout.createSequentialGroup()
                                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personasPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(personasPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(personasPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(diaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(personasPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mesTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellidoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefonoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personasPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(personasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(guardarBTN)
                                    .addComponent(limpiarBTN)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorLog)
                .addGap(26, 26, 26))
        );

        navegacionPanel.addTab("Personas", personasPanel);

        javax.swing.GroupLayout vehiculosPanelLayout = new javax.swing.GroupLayout(vehiculosPanel);
        vehiculosPanel.setLayout(vehiculosPanelLayout);
        vehiculosPanelLayout.setHorizontalGroup(
            vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        vehiculosPanelLayout.setVerticalGroup(
            vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        navegacionPanel.addTab("Vehiculos", vehiculosPanel);

        javax.swing.GroupLayout estacionamientosPanelLayout = new javax.swing.GroupLayout(estacionamientosPanel);
        estacionamientosPanel.setLayout(estacionamientosPanelLayout);
        estacionamientosPanelLayout.setHorizontalGroup(
            estacionamientosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        estacionamientosPanelLayout.setVerticalGroup(
            estacionamientosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        navegacionPanel.addTab("Estacionamientos", estacionamientosPanel);

        javax.swing.GroupLayout PrincipalPanelLayout = new javax.swing.GroupLayout(PrincipalPanel);
        PrincipalPanel.setLayout(PrincipalPanelLayout);
        PrincipalPanelLayout.setHorizontalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navegacionPanel)
        );
        PrincipalPanelLayout.setVerticalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navegacionPanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuiTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuiTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuiTXTActionPerformed

    private void nitTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitTXTActionPerformed

    private void domicilioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicilioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domicilioTXTActionPerformed

    private void diaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaTXTActionPerformed

    private void mesTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesTXTActionPerformed

    private void anioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioTXTActionPerformed

    private void nombreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTXTActionPerformed

    private void apellidoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTXTActionPerformed

    private void telefonoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTXTActionPerformed

    private void guardarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBTNActionPerformed
        this.errorLog.setText("");

        Persona persona = new Persona();

        persona.setNombre(this.nombreTXT.getText());

        if ("".equals(persona.getNombre())) {
            consolePersonalog("Ingresa Nombre", Color.RED);
            return;
        }

        persona.setApellido(this.apellidoTXT.getText());

        if ("".equals(persona.getApellido())) {
            this.errorLog.setText("Ingresa Apellido");
            return;
        }

        persona.setDomicilio(this.domicilioTXT.getText());

        if ("".equals(persona.getDomicilio())) {
            consolePersonalog("Ingresa un domicilio", Color.RED);
            return;
        }

        persona.setCui(Integer.parseInt(this.cuiTXT.getText()));

        persona.setNit(this.nitTXT.getText());

        try {
            persona.setTelefono(Integer.parseInt(this.telefonoTXT.getText()));
        } catch (NumberFormatException e) {
            consolePersonalog("Numero telefonico no valido", Color.RED);
            return;
        }

        try {
            Date fechaNac = new Date(
                    Integer.parseInt(this.anioTXT.getText()),
                    Integer.parseInt(this.mesTXT.getText()),
                    Integer.parseInt(this.diaTXT.getText())
            );

            persona.setFechaNacimiento(fechaNac);
        } catch (Exception e) {
            consolePersonalog("Fecha de Nacimiento no valida", Color.RED);
            return;
        }

        if (this.esNuevo) {
            this.controlador.CrearPersona(persona);
            consolePersonalog("Nueva persona Registrada", Color.GREEN);
            limpiarCampos();
            agregarPersonaTabla(persona);
        } else {
            this.controlador.ActualizarPersona(persona);
            consolePersonalog(" Registro actualizado ", Color.GREEN);
        }


    }//GEN-LAST:event_guardarBTNActionPerformed

    private void limpiarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBTNActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_limpiarBTNActionPerformed

    private void nuevaPersonaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPersonaBTNActionPerformed
        this.limpiarCampos();
        this.PersonaTable.getSelectionModel().clearSelection();
        this.esNuevo = true;

        this.guardarBTN.setText("Registrar");
        this.limpiarBTN.setText("Limpiar");

        this.nitTXT.setEditable(true);
        this.cuiTXT.setEditable(true);
    }//GEN-LAST:event_nuevaPersonaBTNActionPerformed

    private void BuscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBTNActionPerformed
        try {
            Persona persona = controlador.encontrarPersona(Integer.parseInt(this.BuscarTXT.getText()));
            if (persona == null) {
                consolePersonalog("Persona no encontrada", Color.RED);
            }else{
                onEdit(persona);
                                consolePersonalog("Persona encontrada", Color.GREEN);
            }
        } catch (Exception e) {
            System.out.println(e);
            consolePersonalog("Cui no valido", Color.RED);
        }


    }//GEN-LAST:event_BuscarBTNActionPerformed

    private void BuscarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBTN;
    private javax.swing.JTextField BuscarTXT;
    private javax.swing.JTable PersonaTable;
    private javax.swing.JPanel PrincipalPanel;
    private javax.swing.JTextField anioTXT;
    private javax.swing.JTextField apellidoTXT;
    private javax.swing.JTextField cuiTXT;
    private javax.swing.JTextField diaTXT;
    private javax.swing.JTextField domicilioTXT;
    private javax.swing.JLabel errorLog;
    private javax.swing.JPanel estacionamientosPanel;
    private javax.swing.JButton guardarBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarBTN;
    private javax.swing.JTextField mesTXT;
    private javax.swing.JTabbedPane navegacionPanel;
    private javax.swing.JTextField nitTXT;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JButton nuevaPersonaBTN;
    private javax.swing.JPanel personasPanel;
    private javax.swing.JTextField telefonoTXT;
    private javax.swing.JPanel vehiculosPanel;
    // End of variables declaration//GEN-END:variables
}
